[package]
name = "grcov"
version = "0.5.13"
authors = ["Marco Castelluccio <mcastelluccio@mozilla.com>"]
description="Rust tool to collect and aggregate code coverage data for multiple source files"
license="MPL-2.0"
documentation="https://github.com/mozilla/grcov"
homepage="https://github.com/mozilla/grcov"
repository="https://github.com/mozilla/grcov"
readme = "README.md"
keywords=["coverage"]
categories=["command-line-utilities", "development-tools", "development-tools::testing"]
exclude = [
    "test/*",
    "tests/*",
    "benches/*",
    ".travis.yml",
    "appveyor.yml",
    ".gitignore",
    ".dockerignore",
    ".pre-commit-config.yaml",
    "CODE_OF_CONDUCT.md",
]
edition = "2018"

[features]
default = []
tc = ["tcmalloc"]

[badges]
appveyor = { repository = "marco-c/grcov" }
travis-ci = { repository = "mozilla/grcov" }
codecov = { repository = "mozilla/grcov" }

[dependencies]
crossbeam = "^0.7"
serde_json = "^1.0"
walkdir = "^2.3"
num_cpus = "^1.13"
semver = "^0.9"
md-5 = "^0.8"
zip = { version = "^0.5", features = ["deflate-zlib"], default-features = false }
tempfile = "^3"
uuid = { version = "^0.8", features = ["v4"] }
globset = "^0.4"
quick-xml = "^0.18"
smallvec = "^1.3"
rustc-hash = "^1.1"
clap = "^2.32"
fomat-macros = "^0.3"
chrono = "^0.4"
log = "^0.4"
simplelog = "^0.7"

[target.'cfg(unix)'.dependencies]
#tcmalloc = { version = "^0.3", features = ["bundled"] }
tcmalloc = { version = "^0.3", optional = true }

[dev-dependencies]
regex = "^1.3"
